In [2]:
%load_ext autoreload
%autoreload 2

import sys
from pathlib import Path

sys.path.append(str(Path().resolve().parent))

from src.fetch_data import get_sp500_universe, fetch_universe_prices, START_DATE, END_DATE
from src.visualize import build_stock_explorer

import pandas as pd

In [3]:
universe = get_sp500_universe()
universe.head()

  Symbol                  Sector
0    MMM             Industrials
1    AOS             Industrials
2    ABT             Health Care
3   ABBV             Health Care
4    ACN  Information Technology

In [4]:
close, volume = fetch_universe_prices(universe["Symbol"].tolist(), start=START_DATE, end=END_DATE)
close.tail()

Fetching batch 1 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed

Fetching batch 2 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed

Fetching batch 3 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed
[                       0%                       ]

Fetching batch 4 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed

Fetching batch 5 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed

Fetching batch 6 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed

Fetching batch 7 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed

Fetching batch 8 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed

Fetching batch 9 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed

Fetching batch 10 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed

Fetching batch 11 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed

Fetching batch 12 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed

Fetching batch 13 / 13 (23 tickers)...

[*********************100%***********************]  23 of 23 completed

Ticker,A,AAPL,ABBV,ABNB,ABT,ACN,ADBE,ADI,AEE,AEP,...,WST,WTW,WY,WYNN,XEL,XYL,YUM,ZBH,ZBRA,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2026-07-21,132.860001,327.739990,256.100006,144.100006,99.669998,140.860001,227.160004,382.809998,109.940002,130.479996,...,359.005493,288.820007,23.610001,94.629997,78.720001,117.000000,147.169998,88.919998,262.399994,75.349998
2026-07-22,133.460007,325.890015,253.300003,140.050003,100.570000,140.089996,218.360001,386.730011,112.010002,133.070007,...,358.176025,286.510010,23.820000,94.370003,80.190002,116.139999,147.570007,88.680000,262.750000,74.190002
2026-07-23,139.740005,321.660004,256.920013,137.570007,100.750000,138.740005,212.169998,380.200012,113.269997,134.919998,...,355.247955,288.369995,23.639999,96.769997,80.769997,116.870003,147.369995,89.650002,256.950012,74.570000
2026-07-24,138.570007,333.019989,259.359985,141.100006,103.059998,146.990005,225.110001,371.859985,113.779999,135.539993,...,327.985779,295.109985,23.940001,96.919998,81.669998,119.750000,148.919998,91.349998,259.920013,75.349998
2026-07-27,137.889999,336.910004,256.910004,146.860001,104.489998,154.059998,237.750000,371.890015,112.110001,133.589996,...,331.033752,302.640015,23.910000,99.699997,80.709999,120.160004,147.800003,92.070000,264.589996,76.919998

In [6]:
from src.visualize import build_stock_explorer_with_indicators

build_stock_explorer_with_indicators(close, volume=volume, universe=universe)

HBox(children=(Dropdown(description='Ticker:', options=('A (Health Care)', 'AAPL (Information Technology)', 'A…

Output()

In [8]:
from src.fetch_macro_data import fetch_macro_series, save_macro_data, MACRO_SERIES

macro_df = fetch_macro_series(start="2000-01-01")
macro_df.tail()

Fetching GDP (Gross Domestic Product)...
Fetching GDPC1 (Real GDP)...
Fetching INDPRO (Industrial Production Index)...
Fetching RSAFS (Retail Sales)...
Fetching CPIAUCSL (CPI (All Urban Consumers))...
Fetching CPILFESL (Core CPI)...
Fetching PCEPI (PCE Price Index)...
Fetching PCEPILFE (Core PCE Price Index)...
Fetching UNRATE (Unemployment Rate)...
Fetching PAYEMS (Nonfarm Payrolls)...
Fetching ICSA (Initial Jobless Claims)...
Fetching CIVPART (Labor Force Participation Rate)...
Fetching DGS2 (2-Year Treasury Yield)...
Fetching DGS10 (10-Year Treasury Yield)...
Fetching DGS30 (30-Year Treasury Yield)...
Fetching T10Y2Y (10Y-2Y Treasury Spread)...
Fetching FEDFUNDS (Effective Federal Funds Rate)...
Fetching BAMLH0A0HYM2 (High Yield Credit Spread)...
Fetching BAA10Y (Baa Corporate Bond Spread)...
Fetching NFCI (Chicago Fed National Financial Conditions Index)...
Fetching UMCSENT (U. Michigan Consumer Sentiment)...
Fetching VIXCLS (VIX)...
Fetching HOUST (Housing Starts)...
Fetching CSUSHPISA (Case-Shiller Home Price Index)...
Fetching M2SL (M2 Money Supply)...
Fetching DTWEXBGS (Trade Weighted US Dollar Index)...

,GDP,GDPC1,INDPRO,RSAFS,CPIAUCSL,CPILFESL,PCEPI,PCEPILFE,UNRATE,PAYEMS,...,FEDFUNDS,BAMLH0A0HYM2,BAA10Y,NFCI,UMCSENT,VIXCLS,HOUST,CSUSHPISA,M2SL,DTWEXBGS
2026-07-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.84,1.62,NaN,NaN,18.21,NaN,NaN,NaN,120.6247
2026-07-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.87,1.60,NaN,NaN,20.66,NaN,NaN,NaN,120.7892
2026-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.84,1.64,NaN,NaN,17.09,NaN,NaN,NaN,119.6753
2026-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.85,1.63,NaN,NaN,15.99,NaN,NaN,NaN,119.7034
2026-08-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,15.86,NaN,NaN,NaN,NaN

In [9]:
print(f"Shape: {macro_df.shape}")
print(f"Series fetched: {macro_df.columns.tolist()}")
print(f"Missing series (if any): {set(MACRO_SERIES.keys()) - set(macro_df.columns)}")

Shape: (8375, 26)
Series fetched: ['GDP', 'GDPC1', 'INDPRO', 'RSAFS', 'CPIAUCSL', 'CPILFESL', 'PCEPI', 'PCEPILFE', 'UNRATE', 'PAYEMS', 'ICSA', 'CIVPART', 'DGS2', 'DGS10', 'DGS30', 'T10Y2Y', 'FEDFUNDS', 'BAMLH0A0HYM2', 'BAA10Y', 'NFCI', 'UMCSENT', 'VIXCLS', 'HOUST', 'CSUSHPISA', 'M2SL', 'DTWEXBGS']
Missing series (if any): set()

In [10]:
save_macro_data(macro_df)

Saved macro data to /Users/paulgrajzl/Documents/Quant-Projects/alpha-signal-research/data/macro_data.csv

In [11]:
from src.fetch_macro_data import fetch_macro_series, MACRO_SERIES
from src.visualize import build_macro_explorer

macro_df = fetch_macro_series(start="2000-01-01")
build_macro_explorer(macro_df, series_labels=MACRO_SERIES)

Fetching GDP (Gross Domestic Product)...
Fetching GDPC1 (Real GDP)...
Fetching INDPRO (Industrial Production Index)...
Fetching RSAFS (Retail Sales)...
Fetching CPIAUCSL (CPI (All Urban Consumers))...
Fetching CPILFESL (Core CPI)...
Fetching PCEPI (PCE Price Index)...
Fetching PCEPILFE (Core PCE Price Index)...
Fetching UNRATE (Unemployment Rate)...
Fetching PAYEMS (Nonfarm Payrolls)...
Fetching ICSA (Initial Jobless Claims)...
Fetching CIVPART (Labor Force Participation Rate)...
Fetching DGS2 (2-Year Treasury Yield)...
Fetching DGS10 (10-Year Treasury Yield)...
Fetching DGS30 (30-Year Treasury Yield)...
Fetching T10Y2Y (10Y-2Y Treasury Spread)...
Fetching FEDFUNDS (Effective Federal Funds Rate)...
Fetching BAMLH0A0HYM2 (High Yield Credit Spread)...
Fetching BAA10Y (Baa Corporate Bond Spread)...
Fetching NFCI (Chicago Fed National Financial Conditions Index)...
Fetching UMCSENT (U. Michigan Consumer Sentiment)...
Fetching VIXCLS (VIX)...
Fetching HOUST (Housing Starts)...
Fetching CSUSHPISA (Case-Shiller Home Price Index)...
Fetching M2SL (M2 Money Supply)...
Fetching DTWEXBGS (Trade Weighted US Dollar Index)...

HBox(children=(Dropdown(description='Series:', options=('BAA10Y (Baa Corporate Bond Spread)', 'BAMLH0A0HYM2 (H…

Output()