In [2]:
%load_ext autoreload
%autoreload 2

import sys
from pathlib import Path

sys.path.append(str(Path().resolve().parent))

from src.fetch_data import get_sp500_universe, fetch_universe_prices, START_DATE, END_DATE
from src.visualize import build_stock_explorer

import pandas as pd

In [3]:
universe = get_sp500_universe()
universe.head()

  Symbol                  Sector
0    MMM             Industrials
1    AOS             Industrials
2    ABT             Health Care
3   ABBV             Health Care
4    ACN  Information Technology

In [4]:
close, volume = fetch_universe_prices(universe["Symbol"].tolist(), start=START_DATE, end=END_DATE)
close.tail()

Fetching batch 1 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed

Fetching batch 2 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed

Fetching batch 3 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed
[                       0%                       ]

Fetching batch 4 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed

Fetching batch 5 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed

Fetching batch 6 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed

Fetching batch 7 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed

Fetching batch 8 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed

Fetching batch 9 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed

Fetching batch 10 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed

Fetching batch 11 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed

Fetching batch 12 / 13 (40 tickers)...

[*********************100%***********************]  40 of 40 completed

Fetching batch 13 / 13 (23 tickers)...

[*********************100%***********************]  23 of 23 completed

Ticker,A,AAPL,ABBV,ABNB,ABT,ACN,ADBE,ADI,AEE,AEP,...,WST,WTW,WY,WYNN,XEL,XYL,YUM,ZBH,ZBRA,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2026-07-21,132.860001,327.739990,256.100006,144.100006,99.669998,140.860001,227.160004,382.809998,109.940002,130.479996,...,359.005493,288.820007,23.610001,94.629997,78.720001,117.000000,147.169998,88.919998,262.399994,75.349998
2026-07-22,133.460007,325.890015,253.300003,140.050003,100.570000,140.089996,218.360001,386.730011,112.010002,133.070007,...,358.176025,286.510010,23.820000,94.370003,80.190002,116.139999,147.570007,88.680000,262.750000,74.190002
2026-07-23,139.740005,321.660004,256.920013,137.570007,100.750000,138.740005,212.169998,380.200012,113.269997,134.919998,...,355.247955,288.369995,23.639999,96.769997,80.769997,116.870003,147.369995,89.650002,256.950012,74.570000
2026-07-24,138.570007,333.019989,259.359985,141.100006,103.059998,146.990005,225.110001,371.859985,113.779999,135.539993,...,327.985779,295.109985,23.940001,96.919998,81.669998,119.750000,148.919998,91.349998,259.920013,75.349998
2026-07-27,137.889999,336.910004,256.910004,146.860001,104.489998,154.059998,237.750000,371.890015,112.110001,133.589996,...,331.033752,302.640015,23.910000,99.699997,80.709999,120.160004,147.800003,92.070000,264.589996,76.919998

In [6]:
from src.visualize import build_stock_explorer_with_indicators

build_stock_explorer_with_indicators(close, volume=volume, universe=universe)

HBox(children=(Dropdown(description='Ticker:', options=('A (Health Care)', 'AAPL (Information Technology)', 'A…

Output()